include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/errors/**
    - lib/core/shared_widgets/**
    - lib/core/utils/**
    - lib/features/**
    - lib/firebase_options.dart

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true
